### ISSUE TITLE
gradle installDist fails with error

### ISSUE THREAD

**Issue by Radisovik** [cretz/pb-and-k#1]
➜  dev git clone git@github.com:cretz/pb-and-k.git                 
Cloning into 'pb-and-k'...
remote: Counting objects: 938, done.
remote: Compressing objects: 100% (414/414), done.
remote: Total 938 (delta 275), reused 813 (delta 150), pack-reused 0
Receiving objects: 100% (938/938), 194.15 KiB | 10.22 MiB/s, done.
Resolving deltas: 100% (275/275), done.
➜  dev cd pb-and-k 
➜  pb-and-k git:(master) gradle installDist

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':runtime:runtime-common:classes'.
> Task with path 'compileJava' not found in project ':runtime:runtime-common'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
➜  pb-and-k git:(master)

**Comment by Radisvoik** [comment]
➜  pb-and-k git:(master) gradle -version

------------------------------------------------------------
Gradle 4.8.1
------------------------------------------------------------

Build time:   2018-06-21 07:53:06 UTC
Revision:     0abdea078047b12df42e7750ccba34d69b516a22

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0 (Oracle Corporation 25.0-b70)
OS:           Mac OS X 10.13.5 x86_64

➜  pb-and-k git:(master)

**Comment by cretz** [comment]
@Radisovik - you are using installDist on the top level project? Try `gradle :runtime:runtime-jvm:installDist` if you're trying to compile and install the runtime. If this is not what you are trying to do, can you be more clear on what you are trying to accomplish?

**Comment by Radisovik** [comment]
Sorry my copy `n paste of what I was doing didn't show up well.. but yes I was doing a:

"gradle installDist"  from the top level directory.. immediately after cloning.  

I tried doing installDist on the runtimes -- and I get a different error.  For example running "gradle :runtime:runtime-jvm:installDist"

Results in a:


FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDist' not found in project ':runtime:runtime-jvm'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

Perhaps there is a local change on your box letting it work?   or some other simple obvious (not obvious to me.. but to you it is) step that I missed.  I assume I should be able to just clone the library, and then run the gradle target?

**Comment by Radisovik** [comment]
And yes -- I'm just trying to produce the distribution.  I tried to re-use the binary you released -- but when running from the CLI:

`protoc --kotlin_out=src message.proto`

result:

```
Error: Could not find or load main class pbandk.gen.MainKt
--kotlin_out: protoc-gen-kotlin: Plugin failed with status code 1.
```

So I could tell it found your plugin...  else it wouldn't know about the class..   but there was a dependency missing within it, or some error while initializing MainKt...   

(BTW this is all on OSX).

**Comment by Radisovik** [comment]
Thats just a shell script?  I thought it was literally a "binary" like an executable.  Well I didn't install anything else -- no jars or anything.. so its bound to have a classdef problem!  Wait.. I missed the lib directory in the zip file!  ARG   Let me go hide my face in shame...*blush*

**Comment by cretz** [comment]
The goal is to make it a binary executable with Kotlin Native (that's why I separated it out into common and jvm for the code gen) but I didn't do it yet, it's in the TODO.

**Comment by Radisovik** [comment]
Onto my next part..:)   
` protoc --kotlin_out=src message.proto`

I've placed the protoc-gen-kotlin/bin directory on my path... and made sure there aren't any copies of that shell script floating around.... and now....

```
Exception in thread "main" java.lang.VerifyError: Uninitialized object exists on backward branch 306
Exception Details:
  Location:
    pbandk/gen/MainKt.main([Ljava/lang/String;)V @708: goto
  Reason:
    Error exists in the bytecode
 
```
it continues on with the hex dump of the byte code..

**Comment by Radisovik** [comment]
if I run the script directly.. by itself.. I get the same error..  here is the script running with a -x so you can see what java version it picked out..etc...

```
bash -x ./protoc-gen-kotlin
+ PRG=./protoc-gen-kotlin
+ '[' -h ./protoc-gen-kotlin ']'
++ pwd
+ SAVED=/Users/ehubbard/protoc-gen-kotlin-0.1.0/bin
++ dirname ./protoc-gen-kotlin
+ cd ./..
++ pwd -P
+ APP_HOME=/Users/ehubbard/protoc-gen-kotlin-0.1.0
+ cd /Users/ehubbard/protoc-gen-kotlin-0.1.0/bin
+ APP_NAME=protoc-gen-kotlin
++ basename ./protoc-gen-kotlin
+ APP_BASE_NAME=protoc-gen-kotlin
+ DEFAULT_JVM_OPTS=
+ MAX_FD=maximum
+ cygwin=false
+ msys=false
+ darwin=false
+ nonstop=false
+ case "`uname`" in
++ uname
+ darwin=true
+ CLASSPATH=/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/protoc-gen-kotlin-jvm-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/protoc-gen-kotlin-common-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/pbandk-runtime-jvm-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-jdk8-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/pbandk-runtime-common-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-common-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-jdk7-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/protobuf-java-3.5.1.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/annotations-13.0.jar
+ '[' -n /Users/ehubbard/.jenv/versions/oracle64-1.8.0 ']'
+ '[' -x /Users/ehubbard/.jenv/versions/oracle64-1.8.0/jre/sh/java ']'
+ JAVACMD=/Users/ehubbard/.jenv/versions/oracle64-1.8.0/bin/java
+ '[' '!' -x /Users/ehubbard/.jenv/versions/oracle64-1.8.0/bin/java ']'
+ '[' false = false -a true = false -a false = false ']'
+ true
+ GRADLE_OPTS=' "-Xdock:name=protoc-gen-kotlin" "-Xdock:icon=/Users/ehubbard/protoc-gen-kotlin-0.1.0/media/gradle.icns"'
+ false
++ save
++ echo ' '
+ APP_ARGS=' '
+ eval set -- -classpath '"/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/protoc-gen-kotlin-jvm-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/protoc-gen-kotlin-common-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/pbandk-runtime-jvm-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-jdk8-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/pbandk-runtime-common-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-common-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-jdk7-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/protobuf-java-3.5.1.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/annotations-13.0.jar"' pbandk.gen.MainKt ' '
++ set -- -classpath /Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/protoc-gen-kotlin-jvm-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/protoc-gen-kotlin-common-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/pbandk-runtime-jvm-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-jdk8-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/pbandk-runtime-common-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-common-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-jdk7-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/protobuf-java-3.5.1.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/annotations-13.0.jar pbandk.gen.MainKt
++ uname
+ '[' Darwin = Darwin ']'
+ '[' /Users/ehubbard = /Users/ehubbard/protoc-gen-kotlin-0.1.0/bin ']'
+ exec /Users/ehubbard/.jenv/versions/oracle64-1.8.0/bin/java -classpath /Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/protoc-gen-kotlin-jvm-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/protoc-gen-kotlin-common-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/pbandk-runtime-jvm-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-jdk8-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/pbandk-runtime-common-0.1.0.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-common-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-jdk7-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/kotlin-stdlib-1.2.41.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/protobuf-java-3.5.1.jar:/Users/ehubbard/protoc-gen-kotlin-0.1.0/lib/annotations-13.0.jar pbandk.gen.MainKt
Exception in thread "main" java.lang.VerifyError: Uninitialized object exists on backward branch 306
Exception Details:
  Location:
    pbandk/gen/MainKt.main([Ljava/lang/String;)V @708: goto
  Reason:
    Error exists in the bytecode

```

**Comment by cretz** [comment]
My Google searching shows this is a bug in older JDK versions (see [here](https://stackoverflow.com/questions/46837176/kotlin-verifyerror-uninitialized-object-exists-on-backward-branch-90) and [here](https://stackoverflow.com/questions/49515100/gradle-sync-failed-with-android-studio-3-1-uninitialized-object-exists-on-backw). Do you have one of the buggy JDK versions?

**Comment by Radisovik** [comment]
Yap -- looks like a bug in the current version of java that brew (OSX package manager) is using.  I switched over to a newer version and got past that.....

If I run the script directly -- it appears to sit waiting for data on stdin.  Which seems good to me!  :)  I ^C to exit..

But.. if I run:
`protoc --kotlin_out=src message.proto`

I get:

```
protoc-gen-kotlin: program not found or is not executable
--kotlin_out: protoc-gen-kotlin: Plugin failed with status code 1.
```

Need to see what the script is doing when I launch it from protoc.... is there a debug switch or anything on protoc?    

BTW -- I tried running the script from the same working directory from which I ran protoc.. and the script seems to run.. waiting for data on stdin..

**Comment by cretz** [comment]
> it appears to sit waiting for data on stdin. Which seems good to me! :)

Yup, that's how protoc and the plugins communicate which is over stdout. If you are getting "program not found or is not executable" it means that either `protoc-gen-kotlin` is not on the `PATH` or that protoc has the same problem there as on Windows, it doesn't take scripts. If it is on the `PATH` and the issue is the latter, try adding the arg `--plugin=protoc-gen-kotlin=path/to/protoc-gen-kotlin`.

**Comment by Radisovik** [comment]
Same problem as on windows -- 
`protoc --plugin=protoc-gen-kotlin=/Users/ehubbard/protoc-gen-kotlin-0.1.0/bin/protoc-gen-kotlin --kotlin_out=src message.proto`

First time I ran it.. it complained:

`src/: No such file or directory `

Not sure if that is intentional or not.  Once I manually created the directory and re-ran..  I've got myself some kt files!  woohoo!  :)

**Comment by Radisovik** [comment]
BTW -- Thanks for the assistance.  `tis much appreciated.

**Comment by RdeWilde** [comment]
I had the same issues, this info was very helpfull, for example explicitely installing the protoc-gen-kotlin plugin, although it actually is in the documentation, I forgot it.

**Comment by RdeWilde** [comment]
I think it would be a big help to explicitly describe how to place the protoc-gen-kotlin plugin on your buildpath (for example, i extracted it to /usr/local/bin and create a symlink on from usr/local/bin/protoc-gen-kotlin to /usr/local/bin/protoc-gen-kotlin-0.2.0/bin/protoc-gen-kotlin, this DOES NOT work).
Instead I placed the whole root directory in my PATH and then it worked

**Comment by leearmstrong** [comment]
@Radisovik I am using MacOS and getting the same issue as you 

> Error: Could not find or load main class pbandk.gen.MainKt

Where did you place the /lib folder with all the jar files?  Is this what fixed it?
