### ISSUE TITLE
If no package is set then compile fails

### ISSUE THREAD

**Issue by komakai** [cretz/pb-and-k#8]
Since `package` is optional in proto3 - the compiler should be able to handle the case when it is not set.
Steps to reproduce:
 - just remove the package declaration from the `gradle-and-jvm` example app

**Comment by cretz** [comment]
Thanks, I will look into this.

**Comment by komakai** [comment]
> I may not have it fixed and released until early next week.

No really hurry - I just added a package declaration to my proto file to work round the issue

**Comment by cretz** [comment]
Fixed in master, will update when 0.3.0 is released

**Comment by cretz** [comment]
0.3.0 released
